services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "${S3_PORT}:9000"
      - "${S3_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_REGION: ${S3_REGION}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ml-factory-net

  dvc-sync-agent:
    build: ./dvc
    environment:
      GIT_URL: "https://github.com/RvotniyFlex/ml_factory.git"
      DVC_SYNC_S3_BUCKET: "models-bucket"
      DVC_SYNC_S3_PREFIX: "users/"
      AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY}"
      AWS_SECRET_ACCESS_KEY: "${S3_SECRET_KEY}"
      AWS_REGION: "${S3_REGION}"
      DVC_ENDPOINT_URL: "http://minio:9000"
      DVC_SYNC_INTERVAL: 10
      DVC_SYNC_BRANCH: dvc
      DVC_SYNC_LOCAL_DATA_ROOT: data/s3_mirror
    networks:
      - ml-factory-net
    depends_on:
      - minio

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ml-factory-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # внутри докера minio доступен по имени сервиса, а не по localhost
      S3_HOST: minio
      # внешний URL фронта, чтобы редиректы OAuth шли на правильный адрес
      FRONTEND_URL: "${FRONTEND_URL}"
    depends_on:
      - minio
    ports:
      - "8080:8080"
    networks:
      - ml-factory-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ml-factory-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # внутри docker-сети фронт ходит к бэку по имени сервиса
      BACKEND_PUBLIC_URL: "http://localhost:8080"
      BACKEND_ENDPOINT: "${BACKEND_ENDPOINT}"
      FRONTEND_URL: "${FRONTEND_URL}"
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - ml-factory-net

volumes:
  minio_data:

networks:
  ml-factory-net:
    driver: bridge