# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from backend.grpc.contracts import contracts_pb2 as contracts__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in contracts_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class HealthServiceStub(object):
    """=====================
    Health Check
    =====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckApp = channel.unary_unary(
            "/mlfactory.HealthService/CheckApp",
            request_serializer=contracts__pb2.HealthRequest.SerializeToString,
            response_deserializer=contracts__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.CheckS3 = channel.unary_unary(
            "/mlfactory.HealthService/CheckS3",
            request_serializer=contracts__pb2.S3HealthRequest.SerializeToString,
            response_deserializer=contracts__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class HealthServiceServicer(object):
    """=====================
    Health Check
    =====================
    """

    def CheckApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckS3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CheckApp": grpc.unary_unary_rpc_method_handler(
            servicer.CheckApp,
            request_deserializer=contracts__pb2.HealthRequest.FromString,
            response_serializer=contracts__pb2.HealthResponse.SerializeToString,
        ),
        "CheckS3": grpc.unary_unary_rpc_method_handler(
            servicer.CheckS3,
            request_deserializer=contracts__pb2.S3HealthRequest.FromString,
            response_serializer=contracts__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlfactory.HealthService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "mlfactory.HealthService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """=====================
    Health Check
    =====================
    """

    @staticmethod
    def CheckApp(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.HealthService/CheckApp",
            contracts__pb2.HealthRequest.SerializeToString,
            contracts__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckS3(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.HealthService/CheckS3",
            contracts__pb2.S3HealthRequest.SerializeToString,
            contracts__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class UserStorageServiceStub(object):
    """=====================
    User Storage
    =====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDatasets = channel.unary_unary(
            "/mlfactory.UserStorageService/ListDatasets",
            request_serializer=contracts__pb2.UserRequest.SerializeToString,
            response_deserializer=contracts__pb2.DatasetsResponse.FromString,
            _registered_method=True,
        )
        self.ListModels = channel.unary_unary(
            "/mlfactory.UserStorageService/ListModels",
            request_serializer=contracts__pb2.UserModelRequest.SerializeToString,
            response_deserializer=contracts__pb2.ModelsResponse.FromString,
            _registered_method=True,
        )
        self.ListScores = channel.unary_unary(
            "/mlfactory.UserStorageService/ListScores",
            request_serializer=contracts__pb2.UserModelRequest.SerializeToString,
            response_deserializer=contracts__pb2.ScoresResponse.FromString,
            _registered_method=True,
        )


class UserStorageServiceServicer(object):
    """=====================
    User Storage
    =====================
    """

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserStorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListDatasets": grpc.unary_unary_rpc_method_handler(
            servicer.ListDatasets,
            request_deserializer=contracts__pb2.UserRequest.FromString,
            response_serializer=contracts__pb2.DatasetsResponse.SerializeToString,
        ),
        "ListModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListModels,
            request_deserializer=contracts__pb2.UserModelRequest.FromString,
            response_serializer=contracts__pb2.ModelsResponse.SerializeToString,
        ),
        "ListScores": grpc.unary_unary_rpc_method_handler(
            servicer.ListScores,
            request_deserializer=contracts__pb2.UserModelRequest.FromString,
            response_serializer=contracts__pb2.ScoresResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlfactory.UserStorageService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "mlfactory.UserStorageService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class UserStorageService(object):
    """=====================
    User Storage
    =====================
    """

    @staticmethod
    def ListDatasets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.UserStorageService/ListDatasets",
            contracts__pb2.UserRequest.SerializeToString,
            contracts__pb2.DatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.UserStorageService/ListModels",
            contracts__pb2.UserModelRequest.SerializeToString,
            contracts__pb2.ModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListScores(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.UserStorageService/ListScores",
            contracts__pb2.UserModelRequest.SerializeToString,
            contracts__pb2.ScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class DatasetRegistryServiceStub(object):
    """=====================
    Dataset Registry
    =====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsage = channel.unary_unary(
            "/mlfactory.DatasetRegistryService/GetUsage",
            request_serializer=contracts__pb2.UserRequest.SerializeToString,
            response_deserializer=contracts__pb2.UsageResponse.FromString,
            _registered_method=True,
        )
        self.UploadFile = channel.unary_unary(
            "/mlfactory.DatasetRegistryService/UploadFile",
            request_serializer=contracts__pb2.UploadRequest.SerializeToString,
            response_deserializer=contracts__pb2.UploadResponse.FromString,
            _registered_method=True,
        )
        self.DeleteFile = channel.unary_unary(
            "/mlfactory.DatasetRegistryService/DeleteFile",
            request_serializer=contracts__pb2.FileRequest.SerializeToString,
            response_deserializer=contracts__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.LoadSample = channel.unary_unary(
            "/mlfactory.DatasetRegistryService/LoadSample",
            request_serializer=contracts__pb2.FileRequest.SerializeToString,
            response_deserializer=contracts__pb2.LoadResponse.FromString,
            _registered_method=True,
        )


class DatasetRegistryServiceServicer(object):
    """=====================
    Dataset Registry
    =====================
    """

    def GetUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LoadSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DatasetRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetUsage": grpc.unary_unary_rpc_method_handler(
            servicer.GetUsage,
            request_deserializer=contracts__pb2.UserRequest.FromString,
            response_serializer=contracts__pb2.UsageResponse.SerializeToString,
        ),
        "UploadFile": grpc.unary_unary_rpc_method_handler(
            servicer.UploadFile,
            request_deserializer=contracts__pb2.UploadRequest.FromString,
            response_serializer=contracts__pb2.UploadResponse.SerializeToString,
        ),
        "DeleteFile": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFile,
            request_deserializer=contracts__pb2.FileRequest.FromString,
            response_serializer=contracts__pb2.DeleteResponse.SerializeToString,
        ),
        "LoadSample": grpc.unary_unary_rpc_method_handler(
            servicer.LoadSample,
            request_deserializer=contracts__pb2.FileRequest.FromString,
            response_serializer=contracts__pb2.LoadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlfactory.DatasetRegistryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "mlfactory.DatasetRegistryService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DatasetRegistryService(object):
    """=====================
    Dataset Registry
    =====================
    """

    @staticmethod
    def GetUsage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.DatasetRegistryService/GetUsage",
            contracts__pb2.UserRequest.SerializeToString,
            contracts__pb2.UsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UploadFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.DatasetRegistryService/UploadFile",
            contracts__pb2.UploadRequest.SerializeToString,
            contracts__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.DatasetRegistryService/DeleteFile",
            contracts__pb2.FileRequest.SerializeToString,
            contracts__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LoadSample(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.DatasetRegistryService/LoadSample",
            contracts__pb2.FileRequest.SerializeToString,
            contracts__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class ModelServiceStub(object):
    """=====================
    Model Service
    =====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
            "/mlfactory.ModelService/Train",
            request_serializer=contracts__pb2.TrainRequest.SerializeToString,
            response_deserializer=contracts__pb2.TrainResponse.FromString,
            _registered_method=True,
        )
        self.Predict = channel.unary_unary(
            "/mlfactory.ModelService/Predict",
            request_serializer=contracts__pb2.PredictRequest.SerializeToString,
            response_deserializer=contracts__pb2.PredictResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/mlfactory.ModelService/Delete",
            request_serializer=contracts__pb2.DeleteRequest.SerializeToString,
            response_deserializer=contracts__pb2.ModelDeleteResponse.FromString,
            _registered_method=True,
        )


class ModelServiceServicer(object):
    """=====================
    Model Service
    =====================
    """

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Train": grpc.unary_unary_rpc_method_handler(
            servicer.Train,
            request_deserializer=contracts__pb2.TrainRequest.FromString,
            response_serializer=contracts__pb2.TrainResponse.SerializeToString,
        ),
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=contracts__pb2.PredictRequest.FromString,
            response_serializer=contracts__pb2.PredictResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=contracts__pb2.DeleteRequest.FromString,
            response_serializer=contracts__pb2.ModelDeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlfactory.ModelService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("mlfactory.ModelService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """=====================
    Model Service
    =====================
    """

    @staticmethod
    def Train(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.ModelService/Train",
            contracts__pb2.TrainRequest.SerializeToString,
            contracts__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.ModelService/Predict",
            contracts__pb2.PredictRequest.SerializeToString,
            contracts__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlfactory.ModelService/Delete",
            contracts__pb2.DeleteRequest.SerializeToString,
            contracts__pb2.ModelDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
